import { additionalArticles } from './additionalArticles'

export interface Service {
  slug: string
  title: string
  shortDesc: string
  icon: string
  image?: string
}

export interface Article {
  slug: string
  date: string
  title: string
  excerpt: string
  author: string
  category: 'Briefings'
  image: string
  content: string
}

export interface TeamMember {
  slug: string
  name: string
  title: string
  image: string
  bio: string
  email?: string
  phone?: string
}

export const services: Service[] = [
  { slug: 'special-situations-advisory', title: 'Special Situations Advisory', shortDesc: 'Strategic counsel and hands-on support from experienced experts in complex legal, commercial, regulatory, and reputational crises.', icon: 'special-situations', image: '/images/Impartial-Investigation-1.webp' },
  { slug: 'dispute-resolution', title: 'Dispute Resolution', shortDesc: 'Commercial litigation, arbitration, and mediation across multiple jurisdictions.', icon: 'dispute', image: '/images/careers-feature.png' },
  { slug: 'regulatory-and-compliance', title: 'Regulatory and Compliance', shortDesc: 'Deep expertise in regulatory compliance for both contentious and non-contentious situations in today’s complex global environment.', icon: 'regulatory', image: '/images/careers-hero.png' },
  { slug: 'forensic-investigations-and-intelligence', title: 'Forensic Investigations and Intelligence', shortDesc: 'A holistic approach to the management of legal, regulatory, commercial, and reputational risks.', icon: 'forensic', image: '/images/people-hero.jpg' },
  { slug: 'reputation-management-and-crisis-response', title: 'Reputation Management and Crisis Response', shortDesc: 'Multidisciplinary teams dealing with actions and events that threaten businesses, brands, and personal reputations.', icon: 'reputation', image: '/images/bg1.avif' },
  { slug: 'fintech-and-digital-assets-advisory', title: 'Fintech and Digital Assets Advisory', shortDesc: 'Advice on regulation, investigations, digital assets, and complex cryptocurrency disputes.', icon: 'fintech', image: '/images/bg1.avif' },
  { slug: 'civil-fraud', title: 'Civil Fraud', shortDesc: 'Expertise in civil fraud-related investigations, litigation, asset tracing, and recovery.', icon: 'fraud', image: '/images/bg1.avif' },
  { slug: 'private-client-advisory', title: 'Private Client Advisory', shortDesc: 'Specific expertise for high net worth individuals and owner-managed businesses in the UK and internationally.', icon: 'private', image: '/images/bg1.avif' },
]

export const articles: Article[] = [
  { slug: 'we-have-news', date: '02.10.2025', title: 'We have news!', excerpt: 'Parametric Global Consulting is proud to announce that it has officially been certified as a Women\'s Business Enterprise by WEConnect International.', author: 'Parametric Global Consulting', category: 'Briefings', image: '/images/news/we-have-news.png', content: '<p>ParametricGC is proud to announce that we have officially been certified as a Women\'s Business Enterprise (WBE) by WEConnect International.</p><p>This certification verifies that Parametric is at least 51% owned, managed, and controlled by one or more women, affirming its commitment to delivering innovative, competitive solutions to clients and partners worldwide.</p><p>As a newly certified women-owned business, Parametric joins the WEConnect International global network, a vibrant community of over 20,000 women-owned businesses in 135+ markets and 180+ member buyers with a combined annual purchasing power of more than $4 trillion.</p><p>We are excited to be part of this global movement to drive economic opportunity and strengthen supply chains through women-owned businesses. This certification not only validates our ownership but also connects us to a powerful ecosystem of opportunities, learning, and collaboration.</p><p>The certification comes at a time when more companies are recognising the strategic advantage of sourcing from competitive, underutilised suppliers. As a certified business, Parametric is now better positioned to engage with corporate and government buyers who are actively seeking innovative solutions and partners that reflect their commitment to responsible, sustainable sourcing.</p><h2>About WEConnect International</h2><p>WEConnect International is the leading global non-profit dedicated to driving money into the hands of women business owners by connecting them with large corporate, multilateral, and government buyers around the world.</p>' },
  { slug: 'the-triage-process-the-3-rs', date: '02.10.2025', title: 'The Triage Process: The 3 Rs', excerpt: 'Having a triage process as part of your investigation methodology is extremely helpful when assessing how issues will be handled.', author: 'Parametric Global Consulting', category: 'Briefings', image: '/images/news/triage-process.png', content: '<p>Having a triage process as part of your investigation methodology is extremely helpful when assessing how issues will be handled, especially in the context of internal complaints, concerns, allegations and reports. It is all about having a stable system in place.</p><p>Think of your triage process as a three-legged stool; if one leg collapses, the entire structure crumbles. Each stage is just as important as the other.</p><p>Working out which triage process to use, however, is an important consideration. Although it is different for every organisation, at Parametric Global Consulting, we recommend the three Rs: React, Respond, Remediate.</p><h2>Step 1 - React</h2><p>An organisation\'s reaction to concerns is all-important. It sets the tone for how adequately a report will be handled and can make or break trust in an organisation\'s culture and approach to handling misconduct. The organisation should be swift but considered in acknowledging the complaint, as failure to do so may mean employees are forced to escalate their concerns outside the organisation.</p><p>Reacting does not always mean starting a full investigation; it will depend on the severity of the report. Nevertheless, it means always providing reassurance to those who speak up, to ensure they feel heard.</p><h2>Step 2 - Respond</h2><p>Responding adequately once an allegation or concern is raised is as crucial as reacting appropriately. The response should be tailored to the nature of the issue and set out a clear plan of action executed using skilled and trained personnel. A response may later be scrutinised by law enforcement or regulators.</p><h2>Step 3 - Remediate</h2><p>Remediation is the third pillar of the triage structure. It is one of the main reasons for reporting concerns because ultimately, people want something done about them. Poor remediation can damage trust and organisational culture, while effective remediation helps ensure that organisational values and principles remain intact.</p><h2>Takeaways</h2><p>Do you have a clear and effective triage process? The initial reaction to a complaint can either instil confidence or dismantle trust. Failure to respond meaningfully can draw scrutiny from law enforcement and regulators. Organisations that invest in a robust triage process are better equipped to encourage a speak-up culture.</p>' },
  { slug: '2024-end-of-year-reflections', date: '20.12.2024', title: '2024: End of Year Reflections', excerpt: 'As 2024 draws to a close, Parametric Global Consulting reflects on its most dynamic year yet and celebrates its seventh anniversary.', author: 'Parametric Global Consulting', category: 'Briefings', image: '/images/news/reflections-2024.jpg', content: '<h2>Hello Everyone!</h2><p>As 2024 draws to a close, we at Parametric Global Consulting are reflecting on our most dynamic year yet. We are grateful for all that we have achieved and are especially delighted to celebrate our seventh anniversary, a significant milestone.</p><p>The past seven years have been a whirlwind of growth. We have supported existing clients and onboarded new clients, from international institutions to large multi-national organisations, with complex and engaging projects. We have enjoyed supporting our clients in various jurisdictions, and our reputation for handling sensitive, complex investigations involving senior executives has only grown stronger.</p><p>This summer, we were thrilled to welcome four fantastic new members to the Parametric Global Consulting team, with expertise across multiple disciplines, right on time for our anniversary.</p><p>Our Managing Partner, Lloydette Bai-Marrow, also had an exceptional year, delivering international training programmes and workshops in Zambia, Cote d\'Ivoire, and Kenya. We are proud to share that she was a finalist for the Woman of the Year award at the Women and Diversity in Law Awards 2024.</p><p>The UK\'s economic crime landscape continues to evolve, with the new Failure to Prevent Offence coming into force on 1 September 2025. In response to regulatory changes, Parametric Global will be enhancing its thought leadership initiatives and sharing practical resources to support organisations with effective compliance.</p><p>In 2025, we look forward to serving and collaborating with new and existing clients as we continue to build Parametric Global Consulting. We wish you and your loved ones a blessed end to 2024. Merry Christmas and a Happy New Year!</p>' },
  { slug: '2023-end-of-year-reflections', date: '21.12.2023', title: '2023: End Of Year Reflections', excerpt: 'Parametric Global reflects on client work, the launch of The Investigator\'s Mindset podcast, and the year ahead.', author: 'Parametric Global Consulting', category: 'Briefings', image: '/images/news/reflections-2023.jpg', content: '<h2>Hello everyone!</h2><p>2023 has flown by and is almost at an end. Here at Parametric Global, we are thankful and proud of all that we have achieved this year.</p><p>We have continued to support our clients and onboarded new clients, from international institutions to large multi-national companies, with complex and engaging projects. In 2023, we secured one of our biggest clients, providing advisory services and assessing financial crime risk. Over the course of this year, we furthered our reputation for skilfully handling sensitive, complex investigations into allegations against senior executives.</p><p>A highlight of this year includes the launch of our podcast, The Investigator\'s Mindset, dedicated to helping investigators and compliance professionals stay on top of their game. With four episodes released so far, it has had fantastic reception and received almost 600 downloads.</p><p>Our Founding Partner Lloydette Bai-Marrow also had a jam-packed year, including a public panel discussion at the Blavatnik School of Government, University of Oxford, and appointments as a Commissioner of the Gambling Commission and Associate NED for Barnet, Enfield &amp; Haringey Mental Health NHS Trust.</p><p>There have been huge changes to the UK\'s economic crime landscape, including the expansion of corporate criminal liability and the new Economic Crime and Corporate Transparency Act. In January, we planned to launch our corporate investigations and economic crime updates newsletter, Parametric Insights.</p><p>We look forward to working with new and existing clients as we continue to build Parametric Global Consulting. We wish you and your loved ones a blessed end to 2023. Merry Christmas and a Happy New Year!</p>' },
]

export const allArticles: Article[] = [...articles, ...additionalArticles]

export const team: TeamMember[] = [
  { slug: 'sarah-chen', name: 'Sarah Chen', title: 'Managing Partner', image: '/placeholder-team-1.jpg', bio: 'Sarah advises on complex cross-border transactions and leads the firm&apos;s strategic growth initiatives.', email: 's.chen@parametric-legal.com' },
  { slug: 'james-whitfield', name: 'James Whitfield', title: 'Senior Partner, Finance', image: '/placeholder-team-2.jpg', bio: 'James specialises in structured finance, leveraged acquisition facilities, and debt capital markets.', email: 'j.whitfield@parametric-legal.com' },
  { slug: 'elena-rossi', name: 'Elena Rossi', title: 'Partner, Private Client', image: '/placeholder-team-3.jpg', bio: 'Elena leads the private client practice, advising UHNW families on succession, trusts, and tax.', email: 'e.rossi@parametric-legal.com' },
  { slug: 'michael-adeyemi', name: 'Michael Adeyemi', title: 'Partner, Dispute Resolution', image: '/placeholder-team-4.jpg', bio: 'Michael has represented clients in ICC, LCIA, and UNCITRAL arbitrations across three continents.', email: 'm.adeyemi@parametric-legal.com' },
]

export const legalPages = [
  { slug: 'legal-notice', title: 'Legal Notice' },
  { slug: 'privacy-policy', title: 'Privacy Policy' },
  { slug: 'complaints', title: 'Complaints Procedure' },
]
