export interface Person {
  slug: string
  name: string
  title: string
  image: string
  description: string
  biography?: string
}

export const people: Person[] = [
  { slug: 'lloydette-bai-marrow', name: 'Lloydette Bai-Marrow', title: 'Managing Partner', image: '/ceo.jpeg', description: 'Lloydette founded ParametricGC to address a gap she identified through years of practice in corporate investigations and compliance advisory.', biography: 'Lloydette founded ParametricGC to address a gap she identified through years of practice in corporate investigations and compliance advisory: the need for a firm that could deliver genuinely independent investigative and advisory work with the commercial awareness and procedural rigor that complex, sensitive engagements demand. Her career has spanned corporate investigations across multiple sectors and jurisdictions, compliance program design for regulated institutions, and strategic advisory to boards and leadership teams navigating reputational and regulatory crises. She leads the firm\'s most complex mandates personally, and her direct involvement from instruction through to deliverable is central to the standard ParametricGC has built its reputation on.' },
  { slug: 'cecilia-garcia-podoley', name: 'Cecilia Garcia Podoley', title: 'Associate Consultant', image: '/images/people/Cecilia-Garcia-Podoley.webp', description: 'International and multilingual lawyer, Ethics & Compliance Expert, and Certified Fraud Examiner with public and private sector experience.', biography: 'Cecilia Garcia Podoley is an international and multilingual lawyer, Ethics & Compliance Expert, and Certified Fraud Examiner (CFE) with extensive experience across the public and private sectors. She specialises in internal investigations, data protection, risk assessments, strategy, training, AI governance and the ethics of new technologies. She is currently a board member of Ethics & Compliance Switzerland (ECS) and an advisor to several NGOs.' },
  { slug: 'roberto-di-cillo', name: 'Roberto di Cillo', title: 'Associate Consultant', image: '/images/people/Roberto-di-Cillo.webp', description: 'Roberto N. P. di Cillo is a Brazilian lawyer with broad experience in leading and conducting investigations.', biography: 'Roberto N. P. di Cillo is a Brazilian lawyer with broad experience in leading and conducting investigations. He has both in-house and private practice experience gained in the US and Brazil. Roberto is a lecturer, researcher and writer, and an active member of the Brazilian Bar Association\'s São Paulo Section where he is second chair of the Governance and Integrity Permanent Committee.' },
  { slug: 'andrew-clarke', name: 'Andrew Clarke', title: 'Associate Consultant', image: '/images/people/Andrew-Clarke.webp', description: 'Andrew has extensive investigative experience in combating serious crime, including fraud, corruption and money laundering.', biography: 'Andrew has extensive investigative experience in combating serious crime, including fraud, corruption and money laundering. He was a former police detective, and also worked as a Global Lead for financial crime at the foremost international compliance training provider. Andrew has worked on global projects with the United Nations, World Bank and IMF. He specialises in creating and delivering investigation and compliance training courses, and provides business compliance support.' },
  { slug: 'guido-van-drunen', name: 'Guido van Drunen', title: 'Associate Consultant', image: '/images/people/Guido-van-Drunen.webp', description: 'Guido van Drunen is a forensic accounting expert and business strategist with decades of experience in high-profile investigative work.', biography: 'Guido van Drunen is a forensic accounting expert and business strategist with decades of experience in high-profile investigative work. He was a partner at KPMG where he developed the firm\'s forensics practice in the Pacific Northwest and Silicon Valley. He was responsible for a large team investigating fraud, abuse, and intellectual property theft, and worked with a range of clients including Fortune 50 companies. He was also a member of KPMG\'s Partnership Audit Committee. Guido serves as an Adjunct Professor at Santa Clara University and at San Jose State University. He is an author of articles and white papers on a range of financial crime and governance subjects. He has a unique blend of public sector, private sector, and consulting experience along with for profit and nonprofit board experience which allows him to develop unique solutions to various problems.' },
  { slug: 'amani-siddique', name: 'Amani Siddique', title: 'Associate Consultant', image: '/images/people/Amani-Siddique.webp', description: 'Amani graduated from City, University of London in 2020 with a 2:1 in LLB Law with Commercial Law.', biography: 'Amani graduated from City, University of London in 2020 with a 2:1 in LLB Law with Commercial Law. In 2022, Amani joined Parametric Global Consulting after achieving a distinction in the Master of Laws in Legal Practice (LLM LPC) at BPP Law School (2020-2021).' },
  { slug: 'james-badcock', name: 'James Badcock', title: 'Partner', image: '/images/people/James-Badcock_2000z.jpg', description: 'Private client, trusts, estate planning, taxation, governance, and fiduciary risk.' },
  { slug: 'oliver-mishcon', name: 'Oliver Mishcon', title: 'Partner', image: '/images/people/Oliver-Mishcon.jpg', description: 'High-value commercial disputes, white collar crime, regulatory enforcement, and banking.' },
  { slug: 'dhanraj-misra', name: 'Dhanraj Misra', title: 'Partner', image: '/images/people/dhanraj-misra.jpg', description: 'Global disputes strategy, cross-border litigation, arbitration, fraud, and asset recovery.' },
  { slug: 'simon-lewis-obe', name: 'Simon Lewis OBE', title: 'Special Situations Advisor', image: '/images/people/Simon-Lewis-OBE_2000z.jpg', description: 'Strategic communications, crisis response, reputation, and public affairs.' },
  { slug: 'sir-michael-rake', name: 'Sir Michael Rake', title: 'Special Situations Advisor', image: '/images/people/Sir-Michael-Rake_2000z.jpg', description: 'Strategic counsel on complex legal, commercial, financial, and leadership situations.' },
]
